// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzpSLLZfB9V3HCGbGD3JeSNNY2AlyT9I0',
    appId: '1:980244339918:android:e3f2bca235b294cd15449f',
    messagingSenderId: '980244339918',
    projectId: 'photomap-7a945',
    databaseURL: 'https://photomap-7a945.firebaseio.com',
    storageBucket: 'photomap-7a945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtSiSSgipUnLC9tCDcVqCld45NyVfQGCs',
    appId: '1:980244339918:ios:14bcb1b14183618b15449f',
    messagingSenderId: '980244339918',
    projectId: 'photomap-7a945',
    databaseURL: 'https://photomap-7a945.firebaseio.com',
    storageBucket: 'photomap-7a945.appspot.com',
    androidClientId: '980244339918-88qd1bholvqtagk1dvi3fnkh1eeoact1.apps.googleusercontent.com',
    iosClientId: '980244339918-gk4003s7msi4t2p8u5jb95augndesoq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoMapFlutter',
  );
}
